import type { Metadata } from "next";
import "./globals.css";
import AuthWrapper from "@/components/Providers/AuthWrapper";
import SharedBackgroundMusic from '@/components/Common/Audio/SharedBackgroundMusic';
import { AudioProvider } from '@/contexts/AudioContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AudioProvider>
          <SharedBackgroundMusic />
          <AuthWrapper>
            {children}
          </AuthWrapper>
        </AudioProvider>
      </body>
    </html>
  );
}
